version: "3.4"
services:
    redis:
        image: redis:6.0.9-alpine
        container_name: redis
        ports:
            - 6379:6379

    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3.8-management"
        environment:
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        ports:
            - "4369:4369"
            - "15672:15672"
            - "5672:5672"
            - "25672:25672"

    swoole:
        container_name: "swoole"
        depends_on:
            - redis
            - rabbitmq
        environment:
            - "REDIS_SERVER_HOST=redis"
            - "AMQP_SERVER_HOST=rabbitmq"
        build:
            context: .
            dockerfile: ./swoole.dockerfile
            args:
                SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
        volumes:
            - "${GITHUB_WORKSPACE}:/imi:rw"
        working_dir: /imi
        ulimits:
            core: -1
        privileged: true
        command: tail -f /etc/group

    swoole-only:
        container_name: "swoole-only"
        build:
            context: .
            dockerfile: ./swoole.dockerfile
            args:
                SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
        volumes:
            - "${GITHUB_WORKSPACE}:/imi:rw"
        working_dir: /imi
        ulimits:
            core: -1
        privileged: true
        command: tail -f /etc/group
